name: unit_tests
on:
  - pull_request

jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pytest
        run: python -m pip install pytest==6.2.2

      - name: Install python dependencies
        run: python -m pip install -r requirements.txt

      - name: Install QA framework
        run: python setup.py install --user

      - name: Run unit tests
        run: python -m pytest tests/

  windows:
    runs-on: windows-2019
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pytest
        run: python -m pip install pytest==6.2.2

      - name: Install python dependencies
        run: python -m pip install -r requirements.txt

      - name: Install QA framework
        run: python setup.py install --user

      - name: Run unit tests
        run: python -m pytest tests/
